---
server_timezone: Europe/London # For acceptable entries here, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Amend this share specification, to be mounted by fstab
windows_share: //MACHINE.IP.HERE/Ansible