#!/usr/bin/env ansible-playbook
---
# See README.md for usage
- hosts: all
  remote_user: ansible
  become: true

  # Config files
  vars_files:
    - config.yml
    - secrets.yml # Should be encrypted

  # Several roles need to know the "real" Ansible user. These pre-tasks make
  # that possible.
  pre_tasks:
    - name: Get currently logged-in user
      become: false
      command: whoami
      register: whoami_output
      changed_when: false
      tags: always
    - name: Make currently logged-in user available as "playbook_user" variable
      set_fact:
        playbook_user: "{{ whoami_output.stdout }}"  
      tags: always

  tasks:
    - name: Set time zone
      timezone:
        name: "{{ server_timezone }}"
      tags: init

  roles:
    - role: bash
      tags: [bash, init]
    - role: packages
      tags: [packages, init]
    - role: fstab
      tags: [fstab, init]
    - role: python
      tags: [python, init]
    - role: ntp
      tags: [ntp, time, init]
    - role: name
      tags: [name, init]

    # Security
    - role: selinux
      tags: [selinux, security]
    - role: firewall
      tags: [firewall, security]
    - role: ssh
      tags: [ssh, crypto, security, orch]

    # External hardening roles
    - role: devsec.hardening.os_hardening
      tags: [osharden, security]
    - role: devsec.hardening.ssh_hardening
      vars:
        sftp_enabled: true # Ansible prefers to use SFTP to copy files
        sftp_chroot: false
      tags: [sshharden, security]

    # Configure users
    - role: users
      tags: [users]
