---
# EPEL offers Micro and others
- name: Enable the EPEL Repository
  dnf:
    name: epel-release
    state: latest
    update_cache: yes
  when: ansible_facts['distribution']!='OracleLinux'
    
# Oracle has a different name for their version of EPEL
- name: Enable the Oracle Linux EPEL Repository
  dnf:
    name: oracle-epel-release-el8
    state: latest
    update_cache: yes
  when: ansible_facts['distribution']=='OracleLinux'

# CR repo/PowerTools is needed for lynx
- name: Enable the Red Hat CodeReady Repository
  ini_file:
    dest: /etc/yum.repos.d/redhat.repo
    section: codeready-builder-for-rhel-8-x86_64-rpms
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_facts['distribution']=='RedHat'
- name: Enable the Oracle CodeReady Repository
  ini_file:
    dest: /etc/yum.repos.d/oracle-linux-ol8.repo
    section: ol8_codeready_builder
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_facts['distribution']=='OracleLinux'
- name: Enable CentOS8 PowerTools repo
  lineinfile: 
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    create: false # so raise error if not already installed
    regexp: enabled=
    line: enabled=1
  when: ansible_facts['distribution']=='CentOS'

# Note: fzf needs perl
- name: Install preferred packages
  dnf:
    name:
      - bind-utils # for nslookup
      - chrony
      - cifs-utils
      - git
      - golang # Needed by fzf installer; not available by default under WSL
      - gpg
      - jq
      - lynx
      - micro
      - mlocate
      - net-tools
      - nmap
      - pass
      - perl
      - python3
      - python3-pip
      - python3-setuptools # required to pip3 install ansible
      - sshpass # needed to use passwords with Ansible connections
      - tar # Needed by fzf installer; not available by default under WSL
      - telnet # helpful for debugging
      - traceroute
      - tmux
      - unzip
    state: latest
    update_cache: yes

- name: Clone fzf from GitHub
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /opt/fzf
    version: HEAD
  register: fzfInstall

- name: Install fzf
  command:
      cmd: /opt/fzf/install --no-key-bindings --no-completion --no-update-rc
      chdir: /opt/fzf
  when: fzfInstall.changed

- name: Copy .fzf.bash for root and Ansible playbook users
  copy:
    src: .fzf.bash
    dest: '{{ item }}/.fzf.bash'
    mode: 0644
  with_items:
    - /root
    - "/home/{{ playbook_user }}"